 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: Tomav2 - CG traseiro                                        
     # Surfaces =   7
     # Strips   = 148
     # Vortices =1296

  Sref =  330.00       Cref =  6.5465       Bref =  58.864    
  Xref =  27.341       Yref =  0.0000       Zref =  0.0000    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   3.64480     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =  -0.00000
  Mach  =     0.850     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =   0.01228     Cltot =   0.00000     Cl'tot =   0.00000
  CYtot =   0.00000     Cmtot =  -0.00000
  CZtot =  -0.45520     Cntot =  -0.00000     Cn'tot =  -0.00000

  CLtot =   0.45506
  CDtot =   0.01668
  CDvis =   0.01417     CDind = 0.0025143
  CLff  =   0.44765     CDff  = 0.0076433    | Trefftz
  CYff  =   0.00000         e =    0.7948    | Plane  

   aileron         =   0.00000
   elevator        =  -1.89096
   rudder          =   0.00000

   it              =  -1.00000
 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   7.821945    CLb =   0.000000
 y  force CY |    CYa =   0.000000    CYb =  -0.695743
 x' mom.  Cl'|    Cla =  -0.000000    Clb =  -0.175442
 y  mom.  Cm |    Cma =  -1.051942    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =  -0.097078

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =   0.000000    CLq =  11.313237    CLr =  -0.000000
 y  force CY |    CYp =   0.008434    CYq =  -0.000000    CYr =  -0.096639
 x' mom.  Cl'|    Clp =  -0.554290    Clq =  -0.000000    Clr =   0.144372
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -47.596983    Cmr =  -0.000000
 z' mom.  Cn'|    Cnp =  -0.032745    Cnq =   0.000000    Cnr =  -0.181410

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.009427   CLd03 =  -0.000000
 y  force CY |   CYd01 =   0.000336   CYd02 =  -0.000000   CYd03 =  -0.004453
 x' mom.  Cl'|   Cld01 =   0.003481   Cld02 =  -0.000000   Cld03 =  -0.000522
 y  mom.  Cm |   Cmd01 =  -0.000000   Cmd02 =  -0.038937   Cmd03 =   0.000000
 z' mom.  Cn'|   Cnd01 =   0.000239   Cnd02 =   0.000000   Cnd03 =   0.002005
 Trefftz drag| CDffd01 =   0.000000 CDffd02 =   0.000073 CDffd03 =  -0.000000
 span eff.   |    ed01 =  -0.000000    ed02 =   0.025504    ed03 =   0.000000



                  it           g01 
                  ----------------
 z' force CL |   CLg01 =   0.016569
 y  force CY |   CYg01 =  -0.000000
 x' mom.  Cl'|   Clg01 =  -0.000000
 y  mom.  Cm |   Cmg01 =  -0.065082
 z' mom.  Cn'|   Cng01 =   0.000000
 Trefftz drag| CDffg01 =   0.000116
 span eff.   |    eg01 =   0.045434



 Neutral point  Xnp =  28.221713

 Clb Cnr / Clr Cnb  =  -2.270856    (  > 1 if spirally stable )
