
 ---------------------------------------------
 Run case  1:   -unnamed-                              

 alpha        ->  CL          =  0.448300    
 beta         ->  beta        =   0.00000    
 pb/2V        ->  pb/2V       =   0.00000    
 qc/2V        ->  qc/2V       =   0.00000    
 rb/2V        ->  rb/2V       =   0.00000    
 slat         ->  slat        =   0.00000    
 flap         ->  flap        =   0.00000    
 aileron      ->  aileron     =   0.00000    
 elevator     ->  Cm pitchmom =   0.00000    
 rudder       ->  rudder      =   0.00000    

 alpha     = -0.128038E-04 deg                             
 beta      =   0.00000     deg                             
 pb/2V     =   0.00000                                     
 qc/2V     = -0.483042E-24                                 
 rb/2V     =   0.00000                                     
 CL        =  0.448300                                     
 CDo       =  0.142100E-01                                 
 bank      =   0.00000     deg                             
 elevation =   0.00000     deg                             
 heading   =   0.00000     deg                             
 Mach      =  0.850000                                     
 velocity  =   255.038     Lunit/Tunit                     
 density   =  0.419906     Munit/Lunit^3                   
 grav.acc. =   9.81000     Lunit/Tunit^2                   
 turn_rad. =   0.00000     Lunit                           
 load_fac. =   0.00000                                     
 X_cg      =   27.3457     Lunit                           
 Y_cg      =   0.00000     Lunit                           
 Z_cg      =   0.00000     Lunit                           
 mass      =   205928.     Munit                           
 Ixx       =   1.00000     Munit-Lunit^2                   
 Iyy       =   1.00000     Munit-Lunit^2                   
 Izz       =   1.00000     Munit-Lunit^2                   
 Ixy       =   0.00000     Munit-Lunit^2                   
 Iyz       =   0.00000     Munit-Lunit^2                   
 Izx       =   0.00000     Munit-Lunit^2                   
 visc CL_a =   0.00000                                     
 visc CL_u =   0.00000                                     
 visc CM_a =   0.00000                                     
 visc CM_u =   0.00000                                     
